server:
  port: 8080
 
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: customer-service
        uri: lb://customer-service
        predicates:
        - Path=/customer/**
        filters:
        - StripPrefix=1
      - id: order-service
        uri: lb://order-service
        predicates:
        - Path=/order/**
        filters:
        - StripPrefix=1